# Generated by Django 6.0.1 on 2026-03-23 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='member_ship_date',
            new_name='membership_date',
        ),
    ]
